function(BuildFmt)
  set(BUILD_SHARED_LIBS OFF)
  add_subdirectory(${fmt_SOURCE_DIR} ${PROJECT_BINARY_DIR}/fmt_${fmt_VERSION} EXCLUDE_FROM_ALL SYSTEM)
  set_target_properties(fmt PROPERTIES FOLDER ExternalProjectTargets/fmt)
  if (MSVC)
    target_compile_options(fmt PRIVATE /w)
  else()
    target_compile_options(fmt PRIVATE -w)
  endif()
endfunction()
